# Example application-specific west.yml, using manifest imports.
manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
  projects:
    - name: sdk-nrf
      path: nrf
      remote: ncs
      revision: v1.4.2
      import: 
        path-prefix: proj/ncs
  self:
    path: app